export const unreadMessagesCount = state => state.messages.main.length
export const unreadNotificationsCount = state => state.notifications.main.length
export const remainTasksCount = state => state.tasks.main.length
export const currentUser = state => state.user.main
export const totalProduct = state => state.products.main
export const totalProfile = state => state.profiles.main
export const totalCustomer = state => state.customers.main
export const totalOPCenter = state => state.opcenters.main
export const totalRoles = state => state.roles.main
export const totalMenuRoles = state => state.menuroles.main
